# auto-generated by init-project (harness submodule layout)
"""Delegates `python3 harness_cli.py <cmd>` to harness/harness_cli.py.
Auto-generated by `init-project`; do not edit manually.
Re-generate: python3 harness/harness_cli.py init-project --project . --overwrite
"""
import subprocess  # noqa: E401
import sys
import pathlib
_target = pathlib.Path(__file__).parent / "harness" / "harness_cli.py"
raise SystemExit(
    subprocess.run(
        [sys.executable, str(_target), *sys.argv[1:]]
    ).returncode
)
